"""
Feature Families Configuration

Organizes all available features into logical families for feature selection experiments.
Each family groups related features that capture similar aspects of team performance.

Feature naming convention:
  <scope>__<stat>__r<window>__<side>
  - scope: ovr (overall), home (home games only), away (away games only)
  - stat: the underlying statistic
  - window: r3, r5, r10 (rolling window size)
  - side: __h (home team), __a (away team)

Usage:
  from training.feature_families import FEATURE_FAMILIES, get_features_for_families
  
  # Get all features for specific families
  features = get_features_for_families(df, ["xg", "elo", "form"])
"""

from typing import List
import polars as pl


# =============================================================================
# FEATURE FAMILY DEFINITIONS
# =============================================================================
# Each family is defined by the base stat names it covers.
# The actual feature columns are generated by combining:
#   - Scopes: ovr, home, away (for rolling features)
#   - Windows: r3, r5, r10
#   - Sides: __h, __a
#   - Aggregations: mean (default), sum

FEATURE_FAMILIES = {
	# -------------------------------------------------------------------------
	# EXPECTED GOALS (xG) FAMILIES
	# Core predictive features based on shot quality
	# -------------------------------------------------------------------------
	"xg_ovr": {
		"description": "xG metrics (overall scope) - all games regardless of venue",
		"base_stats": ["xg_for", "xg_against", "npxg_for", "npxg_against", "xgd"],
		"scopes": ["ovr"],
		"windows": [3, 5, 10],
		"include_sum": True,
	},
	"xg_venue": {
		"description": "xG metrics (venue-specific) - home/away splits",
		"base_stats": ["xg_for", "xg_against", "npxg_for", "npxg_against", "xgd"],
		"scopes": ["home", "away"],
		"windows": [3, 5, 10],
		"include_sum": True,
	},
	
	# -------------------------------------------------------------------------
	# ACTUAL GOALS FAMILIES
	# Real scoring outcomes
	# -------------------------------------------------------------------------
	"goals_ovr": {
		"description": "Actual goals (overall scope)",
		"base_stats": ["gf", "ga", "gd"],
		"scopes": ["ovr"],
		"windows": [3, 5, 10],
		"include_sum": True,
	},
	"goals_venue": {
		"description": "Actual goals (venue-specific) - home/away splits",
		"base_stats": ["gf", "ga", "gd"],
		"scopes": ["home", "away"],
		"windows": [3, 5, 10],
		"include_sum": True,
	},
	
	# -------------------------------------------------------------------------
	# SHOTS FAMILIES
	# Volume and quality of shooting attempts
	# -------------------------------------------------------------------------
	"shots_ovr": {
		"description": "Shot volume and shots on target (overall scope)",
		"base_stats": ["shots_for", "shots_against", "sot_for", "sot_against"],
		"scopes": ["ovr"],
		"windows": [3, 5, 10],
		"include_sum": True,
	},
	"shots_venue": {
		"description": "Shot volume and shots on target (venue-specific)",
		"base_stats": ["shots_for", "shots_against", "sot_for", "sot_against"],
		"scopes": ["home", "away"],
		"windows": [3, 5, 10],
		"include_sum": True,
	},
	
	# -------------------------------------------------------------------------
	# PRESSING FAMILIES
	# Defensive intensity and territorial dominance
	# -------------------------------------------------------------------------
	"pressing_ovr": {
		"description": "PPDA and deep completions (overall scope)",
		"base_stats": ["ppda_for", "ppda_against", "deep_for", "deep_against"],
		"scopes": ["ovr"],
		"windows": [3, 5, 10],
		"include_sum": True,
	},
	"pressing_venue": {
		"description": "PPDA and deep completions (venue-specific)",
		"base_stats": ["ppda_for", "ppda_against", "deep_for", "deep_against"],
		"scopes": ["home", "away"],
		"windows": [3, 5, 10],
		"include_sum": True,
	},
	
	# -------------------------------------------------------------------------
	# FORM FAMILIES
	# Recent results and momentum
	# -------------------------------------------------------------------------
	"form_ovr": {
		"description": "Points, wins, draws, losses (overall scope)",
		"base_stats": ["points", "win", "draw", "loss"],
		"scopes": ["ovr"],
		"windows": [3, 5, 10],
		"include_sum": True,
	},
	"form_venue": {
		"description": "Points, wins, draws, losses (venue-specific)",
		"base_stats": ["points", "win", "draw", "loss"],
		"scopes": ["home", "away"],
		"windows": [3, 5, 10],
		"include_sum": True,
	},
	
	# -------------------------------------------------------------------------
	# OPPONENT-ADJUSTED FAMILY
	# Performance relative to opponent strength
	# -------------------------------------------------------------------------
	"adjusted": {
		"description": "Opponent-strength adjusted stats (xG, goals, shots) - r10 window only",
		"base_stats": [
			"adj__xg_for", "adj__npxg_for", "adj__gf", "adj__shots_for", "adj__sot_for",
			"adj__xg_against", "adj__npxg_against", "adj__ga", "adj__shots_against", "adj__sot_against"
		],
		"scopes": ["ovr"],  # Only computed for overall
		"windows": [10],  # Only r10 window
		"include_sum": False,  # No sum for adjusted stats
	},
	
	# -------------------------------------------------------------------------
	# ELO FAMILY
	# Team strength ratings and opponent quality
	# -------------------------------------------------------------------------
	"elo": {
		"description": "Elo ratings and opponent strength metrics",
		"special_columns": [
			"elo_diff", "elo_sum", "elo_mean",
			"opponent_elo_r5__h", "opponent_elo_r5__a",
			"elo_diff_r5__h", "elo_diff_r5__a",
			"opponent_elo_std_r5__h", "opponent_elo_std_r5__a",
		],
	},
	
	# -------------------------------------------------------------------------
	# SCHEDULE/CONGESTION FAMILY
	# Fixture density and rest
	# -------------------------------------------------------------------------
	"schedule": {
		"description": "Fixture congestion - rest days and recent game count",
		"special_columns": [
			"days_since_last_match__h", "days_since_last_match__a",
			"games_last_15_days__h", "games_last_15_days__a",
		],
	},
	
	# -------------------------------------------------------------------------
	# SEASON CONTEXT FAMILY
	# Time-in-season features
	# -------------------------------------------------------------------------
	"season_context": {
		"description": "Season progress and round information",
		"special_columns": ["season_progress"],
	},
	
	# -------------------------------------------------------------------------
	# PLAYER AGGREGATES FAMILY
	# Team-level aggregations of player stats
	# -------------------------------------------------------------------------
	"player_agg": {
		"description": "Aggregated player-level xG, assists, shots, key passes",
		"special_columns": [
			"home_team_xg_r15", "away_team_xg_r15",
			"home_team_xa_r15", "away_team_xa_r15",
			"home_team_total_goals_r15", "away_team_total_goals_r15",
			"home_team_total_assists_r15", "away_team_total_assists_r15",
			"home_team_total_shots_r15", "away_team_total_shots_r15",
			"home_team_total_key_passes_r15", "away_team_total_key_passes_r15",
			"home_team_total_minutes_r15", "away_team_total_minutes_r15",
		],
	},
	
	# -------------------------------------------------------------------------
	# SQUAD CONCENTRATION FAMILY
	# Distribution of contributions across squad
	# -------------------------------------------------------------------------
	"squad_concentration": {
		"description": "HHI concentration indices and unique player counts",
		"special_columns": [
			"home_xg_hhi_r15", "away_xg_hhi_r15",
			"home_xa_hhi_r15", "away_xa_hhi_r15",
			"home_minutes_hhi_r15", "away_minutes_hhi_r15",
			"home_unique_players_r15", "away_unique_players_r15",
			"home_unique_players_r5_sum", "away_unique_players_r5_sum",
		],
	},
}


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================


def _generate_rolling_columns(
	base_stats: List[str],
	scopes: List[str],
	windows: List[int],
	include_sum: bool = False,
) -> List[str]:
	"""
	Generate column names for rolling features from base stat definitions.
	
	Returns column patterns like:
	  ovr__xg_for__r5__h, ovr__xg_for__r5__a, home__xg_for__r5__h, away__xg_for__r5__a
	  ovr__xg_for__sum__r5__h, ovr__xg_for__sum__r5__a (if include_sum=True)
	
	Note: For venue-specific scopes (home/away), only valid combinations are generated:
	  - home__*__h: home team's stats from their home games
	  - away__*__a: away team's stats from their away games
	Cross-combinations (home__*__a, away__*__h) are invalid and not generated.
	"""
	columns = []
	for scope in scopes:
		for stat in base_stats:
			for window in windows:
				# For venue-specific scopes, only generate matching side suffix
				if scope == "home":
					sides = ["__h"]  # home stats only for home team
				elif scope == "away":
					sides = ["__a"]  # away stats only for away team
				else:
					sides = ["__h", "__a"]  # ovr scope applies to both
				
				for side in sides:
					# Mean column (no __sum__ in name)
					columns.append(f"{scope}__{stat}__r{window}{side}")
					# Sum column (with __sum__ before window)
					if include_sum:
						columns.append(f"{scope}__{stat}__sum__r{window}{side}")
	return columns


def get_family_columns(family_name: str) -> List[str]:
	"""
	Get all column names for a feature family.
	
	Args:
		family_name: Name of the family (e.g., "xg", "elo", "form")
		
	Returns:
		List of column names belonging to this family
	"""
	if family_name not in FEATURE_FAMILIES:
		raise ValueError(f"Unknown family: {family_name}. Available: {list(FEATURE_FAMILIES.keys())}")
	
	family = FEATURE_FAMILIES[family_name]
	
	# Special columns are explicitly listed
	if "special_columns" in family:
		return family["special_columns"]
	
	# Rolling feature families need column generation
	return _generate_rolling_columns(
		base_stats=family["base_stats"],
		scopes=family["scopes"],
		windows=family["windows"],
		include_sum=family.get("include_sum", False),
	)


def get_features_for_families(
	df: pl.DataFrame,
	families: List[str],
) -> List[str]:
	"""
	Get all feature column names for the specified families that exist in the dataframe.
	
	Args:
		df: DataFrame to check for column existence
		families: List of family names to include
		
	Returns:
		Sorted list of feature column names
	"""
	available_cols = set(df.columns)
	feature_cols = []
	
	for family in families:
		family_cols = get_family_columns(family)
		# Only include columns that exist in the dataframe
		feature_cols.extend([c for c in family_cols if c in available_cols])
	
	return sorted(list(set(feature_cols)))


def get_all_families() -> List[str]:
	"""Return list of all available family names."""
	return list(FEATURE_FAMILIES.keys())


def print_family_summary(df: pl.DataFrame = None):
	"""Print a summary of all feature families and their column counts."""
	print("\n" + "=" * 70)
	print("FEATURE FAMILIES SUMMARY")
	print("=" * 70)
	
	total_features = 0
	for name, family in FEATURE_FAMILIES.items():
		cols = get_family_columns(name)
		
		if df is not None:
			available = [c for c in cols if c in df.columns]
			count_str = f"{len(available)}/{len(cols)} available"
		else:
			available = cols
			count_str = f"{len(cols)} defined"
		
		print(f"\n{name.upper()}: {count_str}")
		print(f"  {family['description']}")
		total_features += len(available)
	
	print("\n" + "-" * 70)
	print(f"TOTAL: {total_features} features across {len(FEATURE_FAMILIES)} families")
	print("=" * 70)


# =============================================================================
# PREDEFINED FEATURE SETS
# =============================================================================
# Common combinations for quick experimentation

FEATURE_SETS = {
	# Minimal: Just xG and Elo (strong baseline)
	"minimal": ["xg_ovr", "elo"],
	
	# Core: Primary predictive features (overall scope only)
	"core": ["xg_ovr", "goals_ovr", "elo", "form_ovr"],
	
	# Standard: What we currently use (ovr__*__r5)
	"standard": ["xg_ovr", "goals_ovr", "shots_ovr", "pressing_ovr", "form_ovr"],
	
	# Full: All team-level rolling features (overall scope)
	"full": ["xg_ovr", "goals_ovr", "shots_ovr", "pressing_ovr", "form_ovr", "adjusted", "elo", "schedule"],
	
	# With venue: Add venue-specific features to standard
	"with_venue": ["xg_ovr", "xg_venue", "goals_ovr", "goals_venue", "shots_ovr", "shots_venue", 
	               "pressing_ovr", "pressing_venue", "form_ovr", "form_venue", "elo", "schedule"],
	
	# Complete: Everything including player aggregates
	"complete": list(FEATURE_FAMILIES.keys()),
}


def get_feature_set(set_name: str, df: pl.DataFrame = None) -> List[str]:
	"""
	Get features for a predefined feature set.
	
	Args:
		set_name: Name of the set ("minimal", "core", "standard", "full", "complete")
		df: Optional DataFrame to filter for existing columns
		
	Returns:
		List of feature column names
	"""
	if set_name not in FEATURE_SETS:
		raise ValueError(f"Unknown set: {set_name}. Available: {list(FEATURE_SETS.keys())}")
	
	families = FEATURE_SETS[set_name]
	
	if df is not None:
		return get_features_for_families(df, families)
	
	# Without df, return all theoretical columns
	all_cols = []
	for family in families:
		all_cols.extend(get_family_columns(family))
	return sorted(list(set(all_cols)))


# =============================================================================
# MAIN - Summary when run directly
# =============================================================================

if __name__ == "__main__":
	from pathlib import Path
	
	parquet_path = Path("data/training/understat_df.parquet")
	
	if parquet_path.exists():
		df = pl.read_parquet(parquet_path)
		print_family_summary(df)
		
		print("\n\nPREDEFINED FEATURE SETS:")
		print("-" * 70)
		for set_name, families in FEATURE_SETS.items():
			cols = get_feature_set(set_name, df)
			print(f"{set_name:12}: {len(cols):3} features from {families}")
	else:
		print(f"Parquet not found at {parquet_path}")
		print_family_summary()
